=== sashokbg/blog/cv/src/cv-data.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "Curriculum Vitae Schema",
  "type": "object",
  "properties": {
    "identity": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        },
        "lastname": {
          "type": "string"
        },
        "role": {
          "type": "string"
        },
        "experience": {
          "type": "string"
        },
        "about": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "education": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "trainings": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "personal_projects": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "languages": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "language": {
                "type": "string"
              },
              "level": {
                "type": "string"
              }
            },
            "required": [
              "language",
              "level"
            ]
          }
        },
        "hobbies": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "contacts": {
          "type": "object",
          "properties": {
            "phone": {
              "type": "string"
            },
            "email": {
              "type": "string",
              "format": "email"
            }
          }
        },
        "links": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "link": {
                "type": "string",
                "format": "uri"
              },
              "ico": {
                "type": "string",
                "description": "Icon for the link: either a URL to an image or a UTF character (emoji)"
              }
            }
          }
        }
      },
      "required": [
        "name",
        "lastname",
        "role",
        "experience"
      ]
    },
    "skills": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "category": {
            "type": "string"
          },
          "items": {
            "type": "array",
            "items": {
              "type": "string"
            }
          }
        },
        "required": [
          "category",
          "items"
        ]
      }
    },
    "timeline": {
      "type": "array",
      "items": {
        "$ref": "#/$defs/timeline_item"
      }
    },
    "experiences": {
      "type": "array",
      "items": {
        "$ref": "#/$defs/experience"
      }
    }
  },
  "required": [
    "identity",
    "skills",
    "timeline",
    "experiences"
  ],
  "$defs": {
    "timeline_item": {
      "type": "object",
      "properties": {
        "year": {
          "type": "integer"
        },
        "role": {
          "type": "string"
        }
      }
    },
    "experience": {
      "type": "object",
      "properties": {
        "start_date": {
          "type": "string",
          "pattern": "^(0[1-9]|1[0-2])-[0-9]{4}$"
        },
        "end_date": {
          "type": "string",
          "pattern": "^(0[1-9]|1[0-2])-[0-9]{4}$"
        },
        "client_name": {
          "type": "string"
        },
        "role": {
          "type": "string"
        },
        "mission_name": {
          "type": "string"
        },
        "mission_image": {
          "type": "string",
          "format": "uri"
        },
        "mission_description": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "roles_and_responsibilities": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "ecosystem": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "team_size": {
          "type": "string"
        },
        "padding": {
          "type": "number",
          "default": 0,
          "description": "Number of empty lines to add at the end to ensure better page break visualization"
        }
      },
      "required": [
        "role",
        "mission_name",
        "client_name",
        "ecosystem",
        "end_date",
        "mission_description",
        "roles_and_responsibilities",
        "start_date",
        "team_size"
      ]
    }
  }
}

=== sashokbg/blog/cv/src/cv-data_bak.json
{
  "identity": {
    "name": "Aleksandar",
    "lastname": "Kirilov",
    "role": "Software Architect",
    "experience": "15 years of experience",
    "contacts": {
      "email": "aleksandar@kirilov.dev",
      "phone": "+33695023765"
    },
    "about": [
      "Passionate about Informatics and Technologies with 15 years of team experience in major companies such as Transdev, Terega, Boursorama, AG2R La Mondiale, GMF, AXA, Priceminister, BforBank, and others.",
      "I am able to lead a project from design to production by implementing a technical solution tailored to the client's situation and constraints.",
      "Enthusiast of best practices, Agile methodology, as well as BDD, DDD, and TDD.",
      "Positive, patient, and pedagogical, enjoying both sharing and explaining, as well as learning from others."
    ],
    "education": [
      "2010 - Ingénieur d’études et besoin, University of Luxembourg"
    ],
    "trainings": [
      "2018: Linux Foundation CKAD: Training course only"
    ],
    "personal_projects": [
      "Home cloud hosting: bare metal k8s",
      "AI Agent for time planning app",
      "BDD Frameworks",
      "Git Exercise Framework",
      "Piano Notes Reading",
      "Personal Blog",
      "Arduino plants watering system"
    ],
    "languages": [
      {
        "language": "Français",
        "level": "C2"
      },
      {
        "language": "Anglais",
        "level": "C1"
      },
      {
        "language": "Bulgare",
        "level": "Native"
      }
    ],
    "hobbies": [
      "Electronics",
      "Informatics",
      "Photography",
      "Table tennis",
      "Guitar"
    ],
    "links": [
      {
        "link": "https://blog.kirilov.dev/",
        "ico": "📝"
      },
      {
        "link": "https://github.com/sashokbg/",
        "ico": "https://github.githubassets.com/assets/GitHub-Mark-ea2971cee799.png"
      },
      {
        "link": "https://www.linkedin.com/in/alexander-kirilov-b0373a62/",
        "ico": "https://upload.wikimedia.org/wikipedia/commons/8/81/LinkedIn_icon.svg"
      }
    ]
  },
  "skills": [
    {
      "category": "Devops & Cloud",
      "items": [
        "GCP",
        "AWS",
        "Azure",
        "Cloud Native (Kubernetes / Docker)",
        "Cloudformation",
        "Terraform / Open Tofu",
        "Ansible",
        "ArgoCD",
        "Helm"
      ]
    },
    {
      "category": "Programming Languages",
      "items": [
        "Java 21/JEE",
        "Javascript",
        "Rust",
        "Typescript",
        "Python",
        "Shell"
      ]
    },
    {
      "category": "AI",
      "items": [
        "Embedding models",
        "Agents",
        "RAG",
        "Knowledge Graphs",
        "Langchain",
        "N8N",
        "Pydantic AI",
        "MCP"
      ]
    },
    {
      "category": "Frameworks",
      "items": [
        "Python Flask",
        "Java Spring",
        "Hibernate – JPA",
        "NodeJs",
        "NestJs",
        "NextJs",
        "React",
        "Angular"
      ]
    },
    {
      "category": "Databases",
      "items": [
        "PostgreSQL",
        "MySQL / Mariadb",
        "Oracle",
        "DynamoDB",
        "H2"
      ]
    },
    {
      "category": "Infra & Tools",
      "items": [
        "Linux",
        "Nginx",
        "Git",
        "Gitlab CI",
        "Bitbucket CI",
        "Maven",
        "Gradle",
        "Nexus",
        "Sonar",
        "Apache",
        "Jenkins",
        "Npm",
        "Taskfile"
      ]
    },
    {
      "category": "Quality",
      "items": [
        "Cucumber",
        "Archunit",
        "EsLint",
        "PyLint",
        "Mockito",
        "Gatling",
        "jMeter",
        "TDD",
        "BDD"
      ]
    }
  ],
  "timeline": [
    {
      "year": 2012,
      "role": "Junior Developer",
      "client": "Boursorama Banque"
    },
    {
      "year": 2013,
      "role": "Junior Developer",
      "client": "AG2R La Mondiale"
    },
    {
      "year": 2015,
      "role": "Developer",
      "client": "GMF"
    },
    {
      "year": 2016,
      "role": "Developer",
      "client": "BforBank"
    },
    {
      "year": 2017,
      "role": "Tech Lead",
      "client": "AXA"
    },
    {
      "year": 2018,
      "role": "Lead Back",
      "client": "Priceminister / Rakuten"
    },
    {
      "year": 2019,
      "role": "Tech Lead / Devops",
      "client": "Pernod Ricard, Point P, Air Liquide"
    },
    {
      "year": 2019,
      "role": "Architect / Devops",
      "client": "Teréga"
    },
    {
      "year": 2019,
      "role": "Architect / Devops",
      "client": "Transdev"
    },
    {
      "year": 2020,
      "role": "Architect / Devops",
      "client": "BforBank"
    },
    {
      "year": 2022,
      "role": "Architect",
      "client": "Bankerise, Proxym"
    },
    {
      "year": 2023,
      "role": "Architect / Devops",
      "client": "Qatar Government"
    },
    {
      "year": 2024,
      "role": "Architect / AI",
      "client": "Proxym AI"
    },
    {
      "year": 2025,
      "role": "Senior Devops",
      "client": "Egis Group"
    },
    {
      "year": 2026,
      "role": "Responsable pôle IA",
      "client": "Proxym"
    }
  ],
  "experiences": [
    {
      "start_date": "05-2026",
      "end_date": "06-2026",
      "client_name": "EGIS Group",
      "role": "Data Engineer",
      "mission_name": "DB Performance Improvements",
      "mission_description": [
        "EGIS digital parking solution offers a BI Dashboard for their clients",
        "The Dashboards are based upon a Data Warehouse, created using a Postgres relational database",
        "The DW suffers from performance issues due to the large size of ingested data and the complexity of certain projections"
      ],
      "roles_and_responsibilities": [
        "Analyse the database schema, queries and stored procedures for potential design and performance issues",
        "Propose an improvement plan, based on the existing architecture and technical constraints",
        "Write and execute stress tests for each use-case"
      ],
      "ecosystem": [
        "SQL Server 2019",
        "MSSQL Extended Events (previously) Profiler",
        ".NET"
      ],
      "team_size": "2p"
    },
    {
      "start_date": "01-2026",
      "end_date": "05-2026",
      "client_name": "Phoenix Fleet Management",
      "role": "Database Analyst",
      "mission_name": "DB Performance Improvements",
      "mission_description": [
        "Analyse and determine origins of performance issues for an on-prem MSSQL 2019 DB",
        "Prepare and present performance reports, based on stress tests",
        "Study the possibility of using AI to further improve the DB performance and speed up deployment"
      ],
      "roles_and_responsibilities": [
        "Analyse the database schema, queries and stored procedures for potential design and performance issues",
        "Propose an improvement plan, based on the existing architecture and technical constraints",
        "Write and execute stress tests for each use-case"
      ],
      "ecosystem": [
        "SQL Server 2019",
        "MSSQL Extended Events (previously) Profiler",
        ".NET"
      ],
      "team_size": "4p"
    },
    {
      "start_date": "05-2025",
      "end_date": "10-2025",
      "client_name": "Egis Group",
      "role": "Senior Devops",
      "mission_name": "Deployment v2 / Cloud Native Database",
      "mission_description": [
        "Modernizing and migrating on-prem and VM infra to cloud native. Preparing ISO 27001 requirements.",
        "Migration of Postgres cluster to Cloud Native Postgres.",
        "Improving time-to-market by optimizing microservices deployment manifests."
      ],
      "roles_and_responsibilities": [
        "Writing disaster recovery plans",
        "Configuring CNPG cluster for Point in Time Recovery",
        "3-2-1 backups strategy for CNPG Postgres",
        "Migrating from Kustomize to Helm Chart",
        "Writing integration tests for IaC",
        "Reorganizing and improving the scripting ecosystem",
        "Coaching and training the team"
      ],
      "ecosystem": [
        "OVH Cloud",
        "Azure",
        "Kubernetes",
        "Microservice architecture"
      ],
      "team_size": "4p"
    },
    {
      "start_date": "05-2024",
      "end_date": "05-2025",
      "client_name": "Proxym",
      "role": "Architect & Author",
      "mission_name": "Product Assistant AI Agent",
      "mission_description": [
        "Author, creator and architect of an application that generates a product’s details page for a PIM system, based on unstructured and multi-modal inputs (text, PDF, Excel, Word, images)."
      ],
      "roles_and_responsibilities": [
        "Implementing a chain of AI-powered tools: embedding models, classification, RAG, LLM function calls and generative models",
        "Developed a smart prompt loader that selects appropriate prompts based on the product’s classification and type",
        "Architecture design of the application",
        "Deployment and infrastructure on Azure Container Apps",
        "BDD scenarios and test automation with Puppeteer",
        "Prospect hunting and client presentations"
      ],
      "ecosystem": [
        "Azure",
        "Container Apps",
        "Puppeteer",
        "LLM",
        "RAG",
        "Agents",
        "LangChain",
        "Pydantic AI",
        "N8N",
        "Knowledge Graphs"
      ],
      "team_size": "5p"
    },
    {
      "start_date": "02-2023",
      "end_date": "05-2024",
      "client_name": "Qatar Government (Ministry of Health)",
      "role": "Architect & Devops",
      "mission_name": "Symptoms Checker",
      "mission_description": [
        "Developed a hybrid healthcare application for the Ministry of Health in Qatar in partnership with Infermedica.",
        "Main objective: enabling patients to perform AI-powered self-diagnosis prior to visiting a specialist physician."
      ],
